name = "fortran_fortress"
version = "0.1.0"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[dev-dependencies]
test-drive = { git = "https://github.com/fortran-lang/test-drive", tag = "v0.6.0" }
